apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - --provider=oidc
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --code-challenge-method=S256
        - --upstream="static://200"
        - --provider-display-name="Sign in with Okta"
        - --client-id=0oao6dkwijey88znZ5d7
        - --client-secret=_TYoW22BmJh60XW8q5SlSkXCW4Hf_HBWs4Zp4U8bpoh7tUBCmjJJvW81WUWfyN-D
        - --redirect-url=https://auth.example.com/oauth2/callback
        - --oidc-issuer-url=https://dev-45536880.okta.com/oauth2/default
        - --cookie-secret=1234567812345678
        - --skip-provider-button=true
        - --reverse-proxy=true
        - --pass-authorization-header=true
        - --whitelist-domain=auth.example.com
        - --cookie-domain=auth.example.com
        - --pass-authorization-header=true
        - --pass-host-header=true
        - --pass-user-headers=true

        # Register a new application  
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
        # resources:
        #   requests:
        #     cpu: "100m"
        #     memory: "128Mi"
        #     ephemeral-storage: "1Gi"
        #   limits:
        #     cpu: "200m"
        #     memory: "256Mi"
        #     ephemeral-storage: "2Gi"
---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  type: NodePort
  ports:
  - name: port80
    port: 80
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
